import { Injectable } from '@angular/core';
import {BookDetails} from "../interfaces/book-details";

@Injectable({
  providedIn: 'root'
})
export class BookingService {
  readonly baseUrl = 'https://angular.dev/assets/images/tutorials/common';

  protected booksDetailsList: BookDetails[] = [
    {
      bookId: 111,
      bookTitle: 'First Test Book1',
      bookAuthor: 'Some Author Test Name1',
      bookPublisher: '',
      bookDescription: '',
      bookYearPublished: '',
      bookCover: '',
      bookInOriginalLanguage: '',
      bookTranslator: '',
      bookISBN: '',
      bookNbrOfPages: 0,
      bookLanguage: '',
      bookVertSize: 0,
      bookHorizSize: 0,
      bookCategories: '',
      photo: `${this.baseUrl}/bernard-hermant-CLKGGwIBTaY-unsplash.jpg`,
    },
    {
      bookId: 222,
      bookTitle: 'First Test Book2',
      bookAuthor: 'Some Author Test Name2',
      bookPublisher: '',
      bookDescription: '',
      bookYearPublished: '',
      bookCover: '',
      bookInOriginalLanguage: '',
      bookTranslator: '',
      bookISBN: '',
      bookNbrOfPages: 0,
      bookLanguage: '',
      bookVertSize: 0,
      bookHorizSize: 0,
      bookCategories: '',
      photo: `${this.baseUrl}/brandon-griggs-wR11KBaB86U-unsplash.jpg`,
    },
    {
      bookId: 333,
      bookTitle: 'First Test Book3',
      bookAuthor: 'Some Author Test Name3',
      bookPublisher: '',
      bookDescription: '',
      bookYearPublished: '',
      bookCover: '',
      bookInOriginalLanguage: '',
      bookTranslator: '',
      bookISBN: '',
      bookNbrOfPages: 0,
      bookLanguage: '',
      bookVertSize: 0,
      bookHorizSize: 0,
      bookCategories: '',
      photo: `${this.baseUrl}/i-do-nothing-but-love-lAyXdl1-Wmc-unsplash.jpg`,
    },
    {
      bookId: 444,
      bookTitle: 'First Test Book4////////////',
      bookAuthor: 'Some Author Test Name4',
      bookPublisher: '',
      bookDescription: '',
      bookYearPublished: '',
      bookCover: '',
      bookInOriginalLanguage: '',
      bookTranslator: '',
      bookISBN: '',
      bookNbrOfPages: 0,
      bookLanguage: '',
      bookVertSize: 0,
      bookHorizSize: 0,
      bookCategories: '',
      photo: `${this.baseUrl}/ian-macdonald-W8z6aiwfi1E-unsplash.jpg`,
    },
    {
      bookId: 555,
      bookTitle: 'First Test Book5',
      bookAuthor: 'Some Author Test Name5',
      bookPublisher: '',
      bookDescription: '',
      bookYearPublished: '',
      bookCover: '',
      bookInOriginalLanguage: '',
      bookTranslator: '',
      bookISBN: '',
      bookNbrOfPages: 0,
      bookLanguage: '',
      bookVertSize: 0,
      bookHorizSize: 0,
      bookCategories: '',
      photo: `${this.baseUrl}/krzysztof-hepner-978RAXoXnH4-unsplash.jpg`,
    },
    {
      bookId: 666,
      bookTitle: 'First Test Book6',
      bookAuthor: 'Some Author Test Name6',
      bookPublisher: '',
      bookDescription: '',
      bookYearPublished: '',
      bookCover: '',
      bookInOriginalLanguage: '',
      bookTranslator: '',
      bookISBN: '',
      bookNbrOfPages: 0,
      bookLanguage: '',
      bookVertSize: 0,
      bookHorizSize: 0,
      bookCategories: '',
      photo: `${this.baseUrl}/phil-hearing-IYfp2Ixe9nM-unsplash.jpg`,
    },
    {
      bookId: 777,
      bookTitle: 'First Test Book7',
      bookAuthor: 'Some Author Test Name7',
      bookPublisher: '',
      bookDescription: '',
      bookYearPublished: '',
      bookCover: '',
      bookInOriginalLanguage: '',
      bookTranslator: '',
      bookISBN: '',
      bookNbrOfPages: 0,
      bookLanguage: '',
      bookVertSize: 0,
      bookHorizSize: 0,
      bookCategories: '',
      photo: `${this.baseUrl}/r-architecture-GGupkreKwxA-unsplash.jpg`,
    },
    {
      bookId: 888,
      bookTitle: 'First Test Book8',
      bookAuthor: 'Some Author Test Name8',
      bookPublisher: '',
      bookDescription: '',
      bookYearPublished: '',
      bookCover: '',
      bookInOriginalLanguage: '',
      bookTranslator: '',
      bookISBN: '',
      bookNbrOfPages: 0,
      bookLanguage: '',
      bookVertSize: 0,
      bookHorizSize: 0,
      bookCategories: '',
      photo: `${this.baseUrl}/saru-robert-9rP3mxf8qWI-unsplash.jpg`,
    },
    {
      bookId: 999,
      bookTitle: 'First Test Book9',
      bookAuthor: 'Some Author Test Name9',
      bookPublisher: '',
      bookDescription: '',
      bookYearPublished: '',
      bookCover: '',
      bookInOriginalLanguage: '',
      bookTranslator: '',
      bookISBN: '',
      bookNbrOfPages: 0,
      bookLanguage: '',
      bookVertSize: 0,
      bookHorizSize: 0,
      bookCategories: '',
      photo: `${this.baseUrl}/webaliser-_TPTXZd9mOo-unsplash.jpg`,
    },
    {
      bookId: 1000,
      bookTitle: 'First Test Book10',
      bookAuthor: 'Some Author Test Name10',
      bookPublisher: '',
      bookDescription: '',
      bookYearPublished: '',
      bookCover: '',
      bookInOriginalLanguage: '',
      bookTranslator: '',
      bookISBN: '',
      bookNbrOfPages: 0,
      bookLanguage: '',
      bookVertSize: 0,
      bookHorizSize: 0,
      bookCategories: '',
      photo: `${this.baseUrl}/bernard-hermant-CLKGGwIBTaY-unsplash.jpg`,
    },
    {
      bookId: 1111,
      bookTitle: 'First Test Book11',
      bookAuthor: 'Some Author Test Name11',
      bookPublisher: '',
      bookDescription: '',
      bookYearPublished: '',
      bookCover: '',
      bookInOriginalLanguage: '',
      bookTranslator: '',
      bookISBN: '',
      bookNbrOfPages: 0,
      bookLanguage: '',
      bookVertSize: 0,
      bookHorizSize: 0,
      bookCategories: '',
      photo: `${this.baseUrl}/phil-hearing-IYfp2Ixe9nM-unsplash.jpg`,
    },
    {
      bookId: 1112,
      bookTitle: 'First Test Book12',
      bookAuthor: 'Some Author Test Name12',
      bookPublisher: '',
      bookDescription: '',
      bookYearPublished: '',
      bookCover: '',
      bookInOriginalLanguage: '',
      bookTranslator: '',
      bookISBN: '',
      bookNbrOfPages: 0,
      bookLanguage: '',
      bookVertSize: 0,
      bookHorizSize: 0,
      bookCategories: '',
      photo: `${this.baseUrl}/phil-hearing-IYfp2Ixe9nM-unsplash.jpg`,
    },
    {
      bookId: 1113,
      bookTitle: 'First Test Book13',
      bookAuthor: 'Some Author Test Name13',
      bookPublisher: '',
      bookDescription: '',
      bookYearPublished: '',
      bookCover: '',
      bookInOriginalLanguage: '',
      bookTranslator: '',
      bookISBN: '',
      bookNbrOfPages: 0,
      bookLanguage: '',
      bookVertSize: 0,
      bookHorizSize: 0,
      bookCategories: '',
      photo: `${this.baseUrl}/ian-macdonald-W8z6aiwfi1E-unsplash.jpg`,
    },
  ];

  getAllBooksDetails(): BookDetails[] {
    return this.booksDetailsList;
  }

  getBookDetailsById(bookID: number): BookDetails | undefined {
    return this.booksDetailsList.find((booksDetailsList)=> booksDetailsList.bookId === bookID);
  }
  constructor() { }
}
